"""
Problem Set 2 - Problem 1, Part 1
Exchange Rate Risk Analysis for European Resident
"""

print("="*80)
print("PROBLEM 1, PART 1: EXCHANGE RATE RISK ANALYSIS")
print("="*80)
print()

print("SCENARIO:")
print("-" * 80)
print("- Dollar exchange rates of euro and yen are EQUALLY VARIABLE")
print("- Euro tends to DEPRECIATE vs dollar when rest of wealth return is HIGH")
print("- Yen tends to APPRECIATE vs dollar when rest of wealth return is HIGH")
print("- Perspective: EUROPEAN RESIDENT")
print("- Question: Which currency is RISKIER - dollar or yen?")
print()

print("="*80)
print("ANALYSIS")
print("="*80)
print()

print("1. UNDERSTANDING RISK FROM A PORTFOLIO PERSPECTIVE")
print("-" * 80)
print("""
As a European resident, we need to consider how currency movements correlate
with the rest of our wealth portfolio. The key concept here is COVARIANCE between
currency returns and portfolio returns.

Risk is not just about volatility (variance) - it's about how an asset moves
relative to your other wealth.
""")
print()

print("2. CORRELATION WITH WEALTH PORTFOLIO")
print("-" * 80)
print()

print("EURO vs DOLLAR (from European perspective):")
print("  • When rest of wealth has unexpectedly HIGH returns → Euro DEPRECIATES vs Dollar")
print("    → Holding dollars means: Good wealth times = Dollar appreciates (good!)")
print("  • When rest of wealth has unexpectedly LOW returns → Euro APPRECIATES vs Dollar")
print("    → Holding dollars means: Bad wealth times = Dollar depreciates (bad!)")
print()
print("  ⇒ Dollar returns are POSITIVELY correlated with wealth portfolio")
print("  ⇒ Dollar acts as a HEDGE - it performs well when you need it!")
print()

print("YEN vs DOLLAR (from European perspective):")
print("  • When rest of wealth has unexpectedly HIGH returns → Yen APPRECIATES vs Dollar")
print("    → Holding dollars means: Good wealth times = Dollar depreciates (bad!)")
print("  • When rest of wealth has unexpectedly LOW returns → Yen DEPRECIATES vs Dollar")
print("    → Holding dollars means: Bad wealth times = Dollar appreciates (good!)")
print()
print("  ⇒ Dollar returns are NEGATIVELY correlated with wealth portfolio")
print("  ⇒ Dollar amplifies risk - loses value when your wealth is already doing poorly!")
print()

print("3. WHICH CURRENCY IS RISKIER?")
print("-" * 80)
print()

print("From a European resident's perspective:")
print()
print("  YEN is RISKIER than DOLLAR")
print()
print("Reasoning:")
print("  • Both currencies have equal variance (equally variable)")
print("  • But COVARIANCE with wealth portfolio differs:")
print()
print("    - DOLLAR: Provides NEGATIVE covariance (hedge)")
print("      → When EUR/USD moves such that dollar strengthens during good times,")
print("         this is helpful as a diversification/insurance")
print()
print("    - YEN: Provides POSITIVE covariance (amplifies risk)")
print("      → When EUR/JPY moves such that yen appreciates during good times,")
print("         holding dollars (yen depreciates vs dollar) means you lose")
print("         on currency when your wealth is already vulnerable")
print()

print("="*80)
print("FORMAL ANALYSIS")
print("="*80)
print()

print("Let's denote:")
print("  • R_W = Return on rest of wealth")
print("  • R_USD = Dollar return (from EUR perspective)")
print("  • R_YEN = Yen return (from EUR perspective)")
print()

print("Given information:")
print("  • Var(R_USD) = Var(R_YEN) = σ² (equal variability)")
print("  • When R_W is HIGH: EUR depreciates vs USD → R_USD is HIGH (positive correlation)")
print("  • When R_W is HIGH: YEN appreciates vs USD → R_USD is LOW (negative correlation)")
print()

print("Therefore:")
print("  • Cov(R_W, R_USD) > 0  (positive covariance)")
print("  • Cov(R_W, R_YEN) < 0  (negative covariance)")
print()

print("Portfolio risk including currency exposure:")
print("  Var(R_Total) = Var(R_W) + Var(R_Currency) + 2·Cov(R_W, R_Currency)")
print()

print("Comparing dollar vs yen investment:")
print()
print("  With DOLLAR:")
print("    Var(R_W + R_USD) = Var(R_W) + σ² + 2·Cov(R_W, R_USD)")
print("                     = Var(R_W) + σ² + 2·(positive)")
print()
print("  With YEN (holding dollars):")
print("    Since yen appreciates when dollar depreciates, holding dollars means")
print("    exposure to yen risk in opposite direction")
print("    This creates HIGHER total portfolio variance")
print()

print("="*80)
print("ANSWER")
print("="*80)
print()
print("For a EUROPEAN RESIDENT:")
print()
print("  THE YEN IS RISKIER THAN THE DOLLAR")
print()
print("Even though both currencies are equally variable, the yen is riskier because:")
print()
print("1. The dollar provides a HEDGE against portfolio risk")
print("   (appreciates when your wealth does well)")
print()
print("2. The yen AMPLIFIES portfolio risk")
print("   (the dollar depreciates against yen when your wealth does poorly)")
print()
print("3. From a portfolio perspective, assets that move in the SAME direction")
print("   as your existing wealth are LESS risky than assets that move in the")
print("   OPPOSITE direction")
print()

print("="*80)
print("ADDITIONAL CONSIDERATIONS")
print("="*80)
print()
print("Ambiguities and assumptions:")
print()
print("1. We interpret 'rest of your wealth' as the European resident's non-currency")
print("   wealth portfolio (stocks, bonds, real estate, etc.)")
print()
print("2. We assume the question asks about holding dollars vs holding yen")
print("   (or equivalently, being exposed to dollar vs yen exchange rate risk)")
print()
print("3. We use modern portfolio theory framework where risk is measured by")
print("   contribution to total portfolio variance")
print()
print("4. Alternative interpretation: If the question asks which currency is riskier")
print("   to SHORT, the answer would be reversed - but the standard interpretation")
print("   is which currency is riskier to HOLD")
print()

print("="*80)
